### ISSUE TITLE
feat: name script file after action name

### ISSUE THREAD

**Issue by Skylli202** [DvdNss/flex-toolbox#3]
Hi,

The title is self-explanatory, I think it would offer a better user experience if the script were named after the action's name.

I think most of us have often quite a few script open in our editor of choice and I end up with this: 
![jetbrains_client64_PWQoMziWUN](https://github.com/DvdNss/flex-toolbox/assets/38432216/9384cabd-df28-4015-906a-48af513f3d19)

Pretty annoying to then know which tab is what script. Especially if you are troubleshooting with multiples times the same script (the action itself and one (or many) jobs of that action).

**Comment by DvdNss** [comment]
agreed that it would be more convenient, issue is naming conventions for actions or workflows etc are not respected most of the times, which results in the toolbox not being able to create the files (ex: [action] Is FSP job Completed?)

had the same issue in the flex-summarizR

would have to figure out how to solve this but even through a regexp I think we would go from 0% of errors to some higher %

**Comment by DvdNss** [comment]
fyi this is why the script name is static (we have a lot of them like this in all environments)

![special_chars](https://github.com/DvdNss/flex-toolbox/assets/50232554/f05c0f42-afed-42be-a440-60a148edbb26)

**Comment by Skylli202** [comment]
INFO: there is an option in IntelliJ to have the folder name
![image](https://github.com/DvdNss/flex-toolbox/assets/38432216/857cc738-cfee-4798-90b3-d898a98edefb)
