### ISSUE TITLE
feat: pulling an empty JEF Script action (new action) does not create the `script.groovy`

### ISSUE THREAD

**Issue by Skylli202** [DvdNss/flex-toolbox#4]
Hi,

I think this use case might be more PS, than CS, but...
We regularly, if not constantly, create new script action. And if you do not create a dummy script in the config tab, then the `script.groovy` file is not created. 

So I could see an automation process were ftbx create the following empty script:
```groovy
import com.ooyala.flex.plugins.PluginCommand

class Script extends PluginCommand {
    def execute () {
        throw new Exception("Not implemented")
    }
}
```

An edge case to think about and discuss, it what happen if this action is pushed back to flex w/o any modification? Is that good, or bad? Should ftbx do a check sum of the default script vs the current script to detect change and say I should update the remote action or not?

**Comment by Skylli202** [comment]
The real question is: can a jef script plugin do not contain any script? I think so in the case of external script ([Flex Scripting: Writing External Scripts](https://support.dalet.com/hc/en-us/articles/5901013978397))

**Comment by DvdNss** [comment]
ftbx create is on the roadmap, allowing you to create items from your IDE (not limited to actions) with a template configuration, so I believe this should be resolved at the same time

**Comment by Skylli202** [comment]
Yup I think it should do the trick. I'll mark this closed once we merge the `feat: ftbx create command` into master.

**Comment by Skylli202** [comment]
You can now create from ftbx, staled.
